apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  # Contraseña de la base de datos. Valor: 'supersecretpassword'
  DB_PASSWORD: "c3VwZXJzZWNyZXRwYXNzd29yZA=="

  # Secreto para firmar los JWT. Valor: 'jwt-secret-key'
  JWT_SECRET: "and0LXNlY3JldC1rZXk="
